<?php
namespace SymfonySimpleSite\User;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;
use SymfonySimpleSite\Common\Interfaces\BundleInterface;

class UserBundle extends Bundle implements BundleInterface
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub
    }

    public static function getConfigName(): string
    {
        return 'user';
    }
}
